# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-01 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/%Y-%m-%d/')),
                ('website_site', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('cited_times', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BrandDataWithCityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_cited_times', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.Brand', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.Category', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='城市名')),
                ('state', models.BooleanField(default=True, verbose_name='可用状态')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='RMB', max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecorationCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='装修公司名称')),
                ('addr', models.CharField(blank=True, max_length=30, null=True, verbose_name='公司地址')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='电话')),
                ('site', models.CharField(blank=True, max_length=50, null=True, verbose_name='公司主页')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_company_set', to='jizhang.City', to_field='name', verbose_name='城市')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.IntegerField(unique=True, verbose_name='省份编码')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='省份名称')),
                ('state', models.BooleanField(default=True, verbose_name='可用状态')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('introduction', models.CharField(blank=True, max_length=200, null=True)),
                ('site', models.URLField(blank=True, null=True, verbose_name='web site')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.City', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='ShopDataWithCityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_cited_times', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.Brand', to_field='name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.City', to_field='name')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.Shop', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='SpendDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('note', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='detail/%Y-%m-%d/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='detail/%Y-%m-%d/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='detail/%Y-%m-%d/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='detail/%Y-%m-%d/')),
                ('created', models.DateTimeField(default='2016-01-01 00:00:00')),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('local_id', models.IntegerField(default=-1)),
                ('addr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.Shop', to_field='name')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.Brand', to_field='name')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.City', to_field='name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='风格')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('cited_times', models.PositiveIntegerField(default=0)),
                ('average_price', models.FloatField(default=0.0)),
                ('min_price', models.FloatField(default=0.0)),
                ('max_price', models.FloatField(default=0.0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_tag_set', to='jizhang.Category', to_field='name')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_tag_set', to='jizhang.City', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='昵称')),
                ('portrayal', models.ImageField(blank=True, null=True, upload_to='user/%Y-%m-%d/', verbose_name='头像')),
                ('signature', models.CharField(default='签名', max_length=30, verbose_name='签名')),
                ('house_area', models.FloatField(default=0.0, verbose_name='面积')),
                ('budget', models.FloatField(blank=True, choices=[('<5万', '<5万'), ('<10万', '<10万'), ('10-15万', '10-15万'), ('15-20万', '15-20万'), ('20-30万', '20-30万'), ('30-50万', '30-50万'), ('50-80万', '50-80万'), ('80-100万', '80-100万'), ('>100万', '>100万')], null=True, verbose_name='预算')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_user_set', to='jizhang.City', to_field='name', verbose_name='城市')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.DecorationCompany', to_field='name', verbose_name='装修公司')),
                ('house_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stype_user_set', to='jizhang.Style', to_field='name', verbose_name='装修风格')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='spenddetail',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.Tag', to_field='name'),
        ),
        migrations.AddField(
            model_name='spenddetail',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.Currency', to_field='name'),
        ),
        migrations.AddField(
            model_name='shopdatawithcitytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.Tag', to_field='name'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_city_set', to='jizhang.Province', to_field='name', verbose_name='所在省份'),
        ),
        migrations.AddField(
            model_name='branddatawithcitytag',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.City', to_field='name'),
        ),
        migrations.AddField(
            model_name='branddatawithcitytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.Tag', to_field='name'),
        ),
    ]
