# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spenddetail',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
