# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.DecorationCompany', to_field='name', verbose_name='装修公司'),
        ),
    ]
