# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branddatawithcitytag',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.Brand', to_field='name', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='branddatawithcitytag',
            name='cited_times',
            field=models.PositiveIntegerField(default=1, verbose_name='引用次数'),
        ),
        migrations.AlterField(
            model_name='branddatawithcitytag',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.City', to_field='name', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='branddatawithcitytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.Tag', to_field='name', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='buyplacedatawithcity',
            name='cited_times',
            field=models.PositiveIntegerField(default=0, verbose_name='引用次数'),
        ),
        migrations.AlterField(
            model_name='spenddetail',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.Brand', to_field='name', verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='spenddetail',
            name='buy_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.BuyPlace', verbose_name='购买地点'),
        ),
        migrations.AlterField(
            model_name='spenddetail',
            name='created',
            field=models.DateTimeField(default='2016-01-01 00:00:00', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='spenddetail',
            name='local_id',
            field=models.IntegerField(default=-1, verbose_name='客户端ID'),
        ),
        migrations.AlterField(
            model_name='spenddetail',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='spenddetail',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='spenddetail',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='spenddetail',
            name='price',
            field=models.FloatField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='spenddetail',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.Tag', to_field='name', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='spenddetail',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.Currency', to_field='name', verbose_name='单位'),
        ),
    ]
