# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spenddetail',
            old_name='addr',
            new_name='buy_pace',
        ),
    ]
