# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityTag2Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cited_times', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.Brand', to_field='name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.City', to_field='name')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.Tag', to_field='name')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 4, 10, 14, 42, 44, 452886), max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='web site'),
        ),
        migrations.AddField(
            model_name='spenddetail',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.Shop', to_field='name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='addr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(default='南京', on_delete=django.db.models.deletion.CASCADE, to='jizhang.City', to_field='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
