# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 22:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=50)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
