# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0002_auto_20160916_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyplacedatawithcity',
            old_name='buy_place',
            new_name='buy_place_name',
        ),
        migrations.AddField(
            model_name='buyplacedatawithcity',
            name='city',
            field=models.ForeignKey(default=datetime.datetime(2016, 9, 16, 9, 59, 32, 34729), on_delete=django.db.models.deletion.CASCADE, to='jizhang.City', to_field='name', verbose_name='城市'),
            preserve_default=False,
        ),

        migrations.AlterUniqueTogether(
            name='buyplacedatawithcity',
            unique_together=set([('city', 'buy_place_name')]),
        ),
    ]
