# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 16:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jizhang', '0002_auto_20160619_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='owner',
            field=models.ForeignKey(default=datetime.datetime(2016, 6, 19, 16, 43, 49, 318403), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
