# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0002_auto_20160410_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDataWithCityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_cited_times', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.Brand', to_field='name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.City', to_field='name')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.Shop', to_field='name')),
            ],
        ),
        migrations.RenameModel(
            old_name='CityTag2Brand',
            new_name='BrandDataWithCityTag',
        ),
        migrations.RenameField(
            model_name='branddatawithcitytag',
            old_name='cited_times',
            new_name='brand_cited_times',
        ),
        migrations.RenameField(
            model_name='spenddetail',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='spenddetail',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jizhang.City', to_field='name'),
        ),
        migrations.AddField(
            model_name='spenddetail',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='detail/'),
        ),
        migrations.AddField(
            model_name='spenddetail',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='detail/'),
        ),
        migrations.AddField(
            model_name='spenddetail',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='detail/'),
        ),
        migrations.AddField(
            model_name='spenddetail',
            name='local_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='tag',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_tag_set', to='jizhang.City', to_field='name'),
        ),
        migrations.AddField(
            model_name='shopdatawithcitytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.Tag', to_field='name'),
        ),
    ]
