# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0003_auto_20160410_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spenddetail',
            old_name='shop',
            new_name='addr',
        ),
        migrations.RemoveField(
            model_name='spenddetail',
            name='local_id',
        ),
    ]
