# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0003_auto_20160916_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyplacedatawithcity',
            name='buy_place_name',
            field=models.CharField(max_length=50, verbose_name='购买地点'),
        ),
        migrations.AlterField(
            model_name='buyplacedatawithcity',
            name='cited_times',
            field=models.PositiveIntegerField(default=1, verbose_name='引用次数'),
        ),
        migrations.AlterField(
            model_name='buyplacedatawithcity',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jizhang.City', to_field='name', verbose_name='所在城市'),
        ),
    ]
