# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0003_auto_20160619_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='house_style',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='decoration_style',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='装修风格'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='house_shape',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='户型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='budget',
            field=models.FloatField(default=0.0, max_length=10, verbose_name='预算'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='装修公司'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(default='我的签名', max_length=30, verbose_name='签名'),
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
