# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0003_auto_20161023_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appversion',
            old_name='cover_end_data',
            new_name='cover_end_date',
        ),
    ]
