# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0004_auto_20160410_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='addr',
        ),
        migrations.AddField(
            model_name='shop',
            name='introduction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
