# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0004_auto_20161023_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='update_log',
            field=models.TextField(blank=True, null=True, verbose_name='更新日志'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='cover_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='封面结束时间'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='cover_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='封面启用时间'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='cover_url',
            field=models.FileField(upload_to='Cover', verbose_name='封面链接'),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='download_url',
            field=models.FileField(upload_to='App', verbose_name='文件链接'),
        ),
    ]
