# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0004_auto_20160916_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyplacedatawithcity',
            name='buy_city',
        ),
    ]
