# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0005_auto_20161025_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spenddetail',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_detail_set', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='用户名'),
        ),
    ]
