# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0005_auto_20160410_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='webite_site',
            new_name='website_site',
        ),
    ]
