# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0006_tagdatawithoutcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='budget',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='预算'),
        ),
    ]
