# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0007_auto_20160922_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='house_area',
            field=models.CharField(default='0.0', max_length=30, verbose_name='面积'),
        ),
    ]
