# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jizhang', '0008_auto_20160925_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyplace',
            name='place_area',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='所在购买城市'),
        ),
        migrations.AlterUniqueTogether(
            name='buyplace',
            unique_together=set([]),
        ),
    ]
